spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  temp:
    dirPath: c:/temp/eb_test/temp
  genFile:
    dirPath: c:/temp/eb_test